#
# Deployment of the Server and celery worker
#
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: data-store
        emptyDir: {}
      containers:
      - name: web
        image: eventyay/api-server:latest
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        livenessProbe:
          httpGet:
            path: /health-check/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: PYTHONUNBUFFERED
          value: 'TRUE'
        - name: DEPLOYMENT
          value: 'web'
        - name: FORCE_SSL
          value: 'yes'
        volumeMounts:
        - mountPath: /opev/open_event/static/uploads/
          name: data-store
      - name: celery
        image: eventyay/api-server:latest
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: DEPLOYMENT
          value: 'celery'
        volumeMounts:
        - mountPath: /opev/open_event/static/uploads/
          name: data-store
      restartPolicy: Always
